// Generated by gencpp from file forces_torques/BodyRequest.msg
// DO NOT EDIT!


#ifndef FORCES_TORQUES_MESSAGE_BODYREQUEST_H
#define FORCES_TORQUES_MESSAGE_BODYREQUEST_H

#include <ros/service_traits.h>


#include <forces_torques/BodyRequestRequest.h>
#include <forces_torques/BodyRequestResponse.h>


namespace forces_torques
{

struct BodyRequest
{

typedef BodyRequestRequest Request;
typedef BodyRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BodyRequest
} // namespace forces_torques


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::forces_torques::BodyRequest > {
  static const char* value()
  {
    return "5eade9afe7f232d78005bd0cafeab755";
  }

  static const char* value(const ::forces_torques::BodyRequest&) { return value(); }
};

template<>
struct DataType< ::forces_torques::BodyRequest > {
  static const char* value()
  {
    return "forces_torques/BodyRequest";
  }

  static const char* value(const ::forces_torques::BodyRequest&) { return value(); }
};


// service_traits::MD5Sum< ::forces_torques::BodyRequestRequest> should match 
// service_traits::MD5Sum< ::forces_torques::BodyRequest > 
template<>
struct MD5Sum< ::forces_torques::BodyRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::forces_torques::BodyRequest >::value();
  }
  static const char* value(const ::forces_torques::BodyRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::forces_torques::BodyRequestRequest> should match 
// service_traits::DataType< ::forces_torques::BodyRequest > 
template<>
struct DataType< ::forces_torques::BodyRequestRequest>
{
  static const char* value()
  {
    return DataType< ::forces_torques::BodyRequest >::value();
  }
  static const char* value(const ::forces_torques::BodyRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::forces_torques::BodyRequestResponse> should match 
// service_traits::MD5Sum< ::forces_torques::BodyRequest > 
template<>
struct MD5Sum< ::forces_torques::BodyRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::forces_torques::BodyRequest >::value();
  }
  static const char* value(const ::forces_torques::BodyRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::forces_torques::BodyRequestResponse> should match 
// service_traits::DataType< ::forces_torques::BodyRequest > 
template<>
struct DataType< ::forces_torques::BodyRequestResponse>
{
  static const char* value()
  {
    return DataType< ::forces_torques::BodyRequest >::value();
  }
  static const char* value(const ::forces_torques::BodyRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FORCES_TORQUES_MESSAGE_BODYREQUEST_H
