// Generated by gencpp from file forces_torques/BodyRequestResponse.msg
// DO NOT EDIT!


#ifndef FORCES_TORQUES_MESSAGE_BODYREQUESTRESPONSE_H
#define FORCES_TORQUES_MESSAGE_BODYREQUESTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace forces_torques
{
template <class ContainerAllocator>
struct BodyRequestResponse_
{
  typedef BodyRequestResponse_<ContainerAllocator> Type;

  BodyRequestResponse_()
    {
    }
  BodyRequestResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::forces_torques::BodyRequestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::forces_torques::BodyRequestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BodyRequestResponse_

typedef ::forces_torques::BodyRequestResponse_<std::allocator<void> > BodyRequestResponse;

typedef boost::shared_ptr< ::forces_torques::BodyRequestResponse > BodyRequestResponsePtr;
typedef boost::shared_ptr< ::forces_torques::BodyRequestResponse const> BodyRequestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::forces_torques::BodyRequestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::forces_torques::BodyRequestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace forces_torques

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::forces_torques::BodyRequestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::forces_torques::BodyRequestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::forces_torques::BodyRequestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::forces_torques::BodyRequestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::forces_torques::BodyRequestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::forces_torques::BodyRequestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::forces_torques::BodyRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::forces_torques::BodyRequestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::forces_torques::BodyRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "forces_torques/BodyRequestResponse";
  }

  static const char* value(const ::forces_torques::BodyRequestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::forces_torques::BodyRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::forces_torques::BodyRequestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::forces_torques::BodyRequestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BodyRequestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::forces_torques::BodyRequestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::forces_torques::BodyRequestResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FORCES_TORQUES_MESSAGE_BODYREQUESTRESPONSE_H
