// Generated by gencpp from file forces_torques/ApplyBodyWrench.msg
// DO NOT EDIT!


#ifndef FORCES_TORQUES_MESSAGE_APPLYBODYWRENCH_H
#define FORCES_TORQUES_MESSAGE_APPLYBODYWRENCH_H

#include <ros/service_traits.h>


#include <forces_torques/ApplyBodyWrenchRequest.h>
#include <forces_torques/ApplyBodyWrenchResponse.h>


namespace forces_torques
{

struct ApplyBodyWrench
{

typedef ApplyBodyWrenchRequest Request;
typedef ApplyBodyWrenchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ApplyBodyWrench
} // namespace forces_torques


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::forces_torques::ApplyBodyWrench > {
  static const char* value()
  {
    return "585b9f9618aa0581b207e2f2d90866bc";
  }

  static const char* value(const ::forces_torques::ApplyBodyWrench&) { return value(); }
};

template<>
struct DataType< ::forces_torques::ApplyBodyWrench > {
  static const char* value()
  {
    return "forces_torques/ApplyBodyWrench";
  }

  static const char* value(const ::forces_torques::ApplyBodyWrench&) { return value(); }
};


// service_traits::MD5Sum< ::forces_torques::ApplyBodyWrenchRequest> should match 
// service_traits::MD5Sum< ::forces_torques::ApplyBodyWrench > 
template<>
struct MD5Sum< ::forces_torques::ApplyBodyWrenchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::forces_torques::ApplyBodyWrench >::value();
  }
  static const char* value(const ::forces_torques::ApplyBodyWrenchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::forces_torques::ApplyBodyWrenchRequest> should match 
// service_traits::DataType< ::forces_torques::ApplyBodyWrench > 
template<>
struct DataType< ::forces_torques::ApplyBodyWrenchRequest>
{
  static const char* value()
  {
    return DataType< ::forces_torques::ApplyBodyWrench >::value();
  }
  static const char* value(const ::forces_torques::ApplyBodyWrenchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::forces_torques::ApplyBodyWrenchResponse> should match 
// service_traits::MD5Sum< ::forces_torques::ApplyBodyWrench > 
template<>
struct MD5Sum< ::forces_torques::ApplyBodyWrenchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::forces_torques::ApplyBodyWrench >::value();
  }
  static const char* value(const ::forces_torques::ApplyBodyWrenchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::forces_torques::ApplyBodyWrenchResponse> should match 
// service_traits::DataType< ::forces_torques::ApplyBodyWrench > 
template<>
struct DataType< ::forces_torques::ApplyBodyWrenchResponse>
{
  static const char* value()
  {
    return DataType< ::forces_torques::ApplyBodyWrench >::value();
  }
  static const char* value(const ::forces_torques::ApplyBodyWrenchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FORCES_TORQUES_MESSAGE_APPLYBODYWRENCH_H
